### ISSUE TITLE
Warning generated in log file

### ISSUE THREAD

**Issue by ilchimicopazzo** [Mira047/FurnitureEngine#1]
Hi, 
thank you for this funny plugin! 
I have installed on a update Paper personal server equipped with openjdk 17.0.1 2021-10-19 on a Raspbian 64bit and I found this warning in the log file.

*********************************
[12:38:10] [Craft Scheduler Thread - 32 - HappyNewYear/WARN]: [HappyNewYear] Plugin HappyNewYear v2.0 generated an exception while executing task 11
java.lang.IllegalStateException: TimeSkipEvent may only be triggered synchronously.
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:616) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R1.CraftWorld.setFullTime(CraftWorld.java:791) ~[paper-1.18.1.jar:git-Paper-124]
	at org.bukkit.craftbukkit.v1_18_R1.CraftWorld.setTime(CraftWorld.java:779) ~[paper-1.18.1.jar:git-Paper-124]
	at com.xSavior_of_God.HappyNewYear.AlwayNight$2.run(AlwayNight.java:49) ~[HappyNewYear 2.0.jar:?]
	at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.18.1.jar:git-Paper-124]
	at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.18.1.jar:git-Paper-124]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.18.1.jar:git-Paper-124]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
*****************************************

This message is generated about 10 time per second.

I hope that you can fix this behaviour.

Cheers,
Andrea

**Comment by Jess077** [comment]
Hello I'm afraid you're in the wrong place! The issue seems to be from a plugin called HappyNewYear, which is unrelated to my work.
